version: '3'

services:
  web:
    build: .
    command: pipenv run gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: pipenv run celery -A tasks worker
    volumes:
      - ./:/app/
    depends_on:
      - redis

    