"""Add schedule to rolling emailers

Revision ID: 7a77a7939df4
Revises: 
Create Date: 2023-05-12 13:36:51.235251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a77a7939df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolling_emailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolling_emailer', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
