"""Remove schedule change to webhook

Revision ID: 950056e311c2
Revises: 7a77a7939df4
Create Date: 2023-05-12 14:26:51.652560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950056e311c2'
down_revision = '7a77a7939df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolling_emailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook', sa.String(), nullable=True))
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolling_emailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.INTEGER(), nullable=True))
        batch_op.drop_column('webhook')

    # ### end Alembic commands ###
