"""empty message

Revision ID: bd49f86df648
Revises: 51160d2f14d6
Create Date: 2023-05-25 08:51:54.548618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd49f86df648'
down_revision = '51160d2f14d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolling_emailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delay_mins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolling_emailer', schema=None) as batch_op:
        batch_op.drop_column('delay_mins')

    # ### end Alembic commands ###
